/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PadronRouteImport } from './routes/padron'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasIdRouteImport } from './routes/noticias.$id'
import { Route as EstudiantesVideosInstructivosRouteImport } from './routes/estudiantes.videos-instructivos'
import { Route as EstudiantesPlanesDeEstudioRouteImport } from './routes/estudiantes.planes-de-estudio'
import { Route as EstudiantesEmprendimientosRouteImport } from './routes/estudiantes.emprendimientos'
import { Route as EstudiantesDescuentosRouteImport } from './routes/estudiantes.descuentos'
import { Route as EstudiantesCertificadosRouteImport } from './routes/estudiantes.certificados'

const PadronRoute = PadronRouteImport.update({
  id: '/padron',
  path: '/padron',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIdRoute = NoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesVideosInstructivosRoute =
  EstudiantesVideosInstructivosRouteImport.update({
    id: '/estudiantes/videos-instructivos',
    path: '/estudiantes/videos-instructivos',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstudiantesPlanesDeEstudioRoute =
  EstudiantesPlanesDeEstudioRouteImport.update({
    id: '/estudiantes/planes-de-estudio',
    path: '/estudiantes/planes-de-estudio',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstudiantesEmprendimientosRoute =
  EstudiantesEmprendimientosRouteImport.update({
    id: '/estudiantes/emprendimientos',
    path: '/estudiantes/emprendimientos',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstudiantesDescuentosRoute = EstudiantesDescuentosRouteImport.update({
  id: '/estudiantes/descuentos',
  path: '/estudiantes/descuentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesCertificadosRoute = EstudiantesCertificadosRouteImport.update({
  id: '/estudiantes/certificados',
  path: '/estudiantes/certificados',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/padron': typeof PadronRoute
  '/estudiantes/certificados': typeof EstudiantesCertificadosRoute
  '/estudiantes/descuentos': typeof EstudiantesDescuentosRoute
  '/estudiantes/emprendimientos': typeof EstudiantesEmprendimientosRoute
  '/estudiantes/planes-de-estudio': typeof EstudiantesPlanesDeEstudioRoute
  '/estudiantes/videos-instructivos': typeof EstudiantesVideosInstructivosRoute
  '/noticias/$id': typeof NoticiasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/padron': typeof PadronRoute
  '/estudiantes/certificados': typeof EstudiantesCertificadosRoute
  '/estudiantes/descuentos': typeof EstudiantesDescuentosRoute
  '/estudiantes/emprendimientos': typeof EstudiantesEmprendimientosRoute
  '/estudiantes/planes-de-estudio': typeof EstudiantesPlanesDeEstudioRoute
  '/estudiantes/videos-instructivos': typeof EstudiantesVideosInstructivosRoute
  '/noticias/$id': typeof NoticiasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/padron': typeof PadronRoute
  '/estudiantes/certificados': typeof EstudiantesCertificadosRoute
  '/estudiantes/descuentos': typeof EstudiantesDescuentosRoute
  '/estudiantes/emprendimientos': typeof EstudiantesEmprendimientosRoute
  '/estudiantes/planes-de-estudio': typeof EstudiantesPlanesDeEstudioRoute
  '/estudiantes/videos-instructivos': typeof EstudiantesVideosInstructivosRoute
  '/noticias/$id': typeof NoticiasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/padron'
    | '/estudiantes/certificados'
    | '/estudiantes/descuentos'
    | '/estudiantes/emprendimientos'
    | '/estudiantes/planes-de-estudio'
    | '/estudiantes/videos-instructivos'
    | '/noticias/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/padron'
    | '/estudiantes/certificados'
    | '/estudiantes/descuentos'
    | '/estudiantes/emprendimientos'
    | '/estudiantes/planes-de-estudio'
    | '/estudiantes/videos-instructivos'
    | '/noticias/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/padron'
    | '/estudiantes/certificados'
    | '/estudiantes/descuentos'
    | '/estudiantes/emprendimientos'
    | '/estudiantes/planes-de-estudio'
    | '/estudiantes/videos-instructivos'
    | '/noticias/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PadronRoute: typeof PadronRoute
  EstudiantesCertificadosRoute: typeof EstudiantesCertificadosRoute
  EstudiantesDescuentosRoute: typeof EstudiantesDescuentosRoute
  EstudiantesEmprendimientosRoute: typeof EstudiantesEmprendimientosRoute
  EstudiantesPlanesDeEstudioRoute: typeof EstudiantesPlanesDeEstudioRoute
  EstudiantesVideosInstructivosRoute: typeof EstudiantesVideosInstructivosRoute
  NoticiasIdRoute: typeof NoticiasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/padron': {
      id: '/padron'
      path: '/padron'
      fullPath: '/padron'
      preLoaderRoute: typeof PadronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$id': {
      id: '/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof NoticiasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/videos-instructivos': {
      id: '/estudiantes/videos-instructivos'
      path: '/estudiantes/videos-instructivos'
      fullPath: '/estudiantes/videos-instructivos'
      preLoaderRoute: typeof EstudiantesVideosInstructivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/planes-de-estudio': {
      id: '/estudiantes/planes-de-estudio'
      path: '/estudiantes/planes-de-estudio'
      fullPath: '/estudiantes/planes-de-estudio'
      preLoaderRoute: typeof EstudiantesPlanesDeEstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/emprendimientos': {
      id: '/estudiantes/emprendimientos'
      path: '/estudiantes/emprendimientos'
      fullPath: '/estudiantes/emprendimientos'
      preLoaderRoute: typeof EstudiantesEmprendimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/descuentos': {
      id: '/estudiantes/descuentos'
      path: '/estudiantes/descuentos'
      fullPath: '/estudiantes/descuentos'
      preLoaderRoute: typeof EstudiantesDescuentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/certificados': {
      id: '/estudiantes/certificados'
      path: '/estudiantes/certificados'
      fullPath: '/estudiantes/certificados'
      preLoaderRoute: typeof EstudiantesCertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PadronRoute: PadronRoute,
  EstudiantesCertificadosRoute: EstudiantesCertificadosRoute,
  EstudiantesDescuentosRoute: EstudiantesDescuentosRoute,
  EstudiantesEmprendimientosRoute: EstudiantesEmprendimientosRoute,
  EstudiantesPlanesDeEstudioRoute: EstudiantesPlanesDeEstudioRoute,
  EstudiantesVideosInstructivosRoute: EstudiantesVideosInstructivosRoute,
  NoticiasIdRoute: NoticiasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
